// Generated by CoffeeScript 1.10.0
var browseSync, del, gulp, minifyCss, runSequence, uglify;

gulp = require('gulp');

runSequence = require('run-sequence');

uglify = require('gulp-uglify');

minifyCss = require('gulp-minify-css');

del = require('del');

browseSync = require('browser-sync').create();

gulp.task('default', function(callback) {
  return runSequence(['clean'], ['build'], ['serve', 'watch'], callback);
});

gulp.task('clean', function(callback) {
  return del(['./disk/'], callback);
});

gulp.task('build', function(callback) {
  return runSequence(['copy', 'miniJS', 'miniCss'], callback);
});

gulp.task('copy', function() {
  return gulp.src('./src/**/*.*').pipe(gulp.dest('./dist/'));
});

gulp.task('miniJS', function() {
  return gulp.src('./src/**/*.js').pipe(uglify()).pipe(gulp.dest('./dist'));
});

gulp.task('miniCss', function() {
  return gulp.src('./src/**/*.css').pipe(minifyCss()).pipe(gulp.dest('./dist'));
});

gulp.task('concat', function() {
  return gulp.src('./src/*.js').pipe(concat('all.js', {
    newLine: ':\n'
  })).pipe(gulp.dest('./dist'));
});

gulp.task('serve', function() {
  return browseSync.init({
    server: {
      baseDir: './dist'
    },
    port: 7411
  });
});

gulp.task('watch', function() {
  return gulp.watch('./src/**/*.*', ['reload']);
});

gulp.task('reload', function(callback) {
  return runSequence(['build'], ['reload-browser'], callback);
});

gulp.task('reload-browser', function() {
  return browseSync.reload();
});
